swagger: "2.0"
info:
  description: "Fin is an application used to keep track of financial account transactions and deposits"
  version: "1.0.0"
  title: "Fin"
  contact:
    email: "sita.robinson@gmail.com"
host: "localhost:8080"
basePath: "/fin-accounts.webservice"
tags:
- name: "user"
  description: "Operations performed on the user"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "accounts"
  description: "Operations performed on accounts"
- name: "transactions"
  description: "Operations performed on transactions"

schemes:
- "https"
- "http"
paths:
  /users:
    get:
      tags:
      - "user"
      summary: "Get a user by userID in the database"
      description: ""
      operationId: "findUsers"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "query"
        name: "userID"
        type: "number"
        description: "A userID for the user"
        required: true
      responses:
        "200":
          description: "Successful response"
          schema: 
            $ref: "#/definitions/User"
        "401":
          description: "Unauthorized"
        "400":
          description: "Bad Request"
  /accounts:
    get:
      tags:
      - "accounts"
      summary: "Get a list of all the accounts by user in the database"
      description: ""
      operationId: "findAccounts"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "query"
        name: "userID"
        type: "number"
        description: "A userID for the user"
        required: true
      responses:
        "200":
          description: "Successful response"
          schema: 
            $ref: "#/definitions/Account"
        "401":
          description: "Unauthorized"
        "400":
          description: "Bad Request"
definitions:
  User:
    type: array
    items: 
      type: "object"
      properties:
        user_id:
          type: "integer"
          format: "int64"
          description: "Unique identifier of user"
          example: 1
        email:
          type: "string"
          description: "Email of User"
          example: "blahworld@gmail.com"
        fullName:
          type: "string"
          description: "Full name of user"
      xml:
        name: "item"
  Account:
    type: array
    items: 
      type: "object"
      properties:
        account_id:
          type: "integer"
          format: "int64"
          description: "Unique identifier of account"
          example: 1
        user_id:
          type: "integer"
          format: "int64"
          description: "Unique identifier of user"
          example: 1
        deposit_amount:
          type: "number"
          description: "Deposits in the account"
          example: 500
        withdraw_amount:
          type: "number"
          description: "Withdraws in the account"
          example: 200
        account_Starting_Amount:
          type: "number"
          description: "Amount the user starts with in the account"
          example: 1000
        account_Description:
          type: "string"
          description: "Short description of the account"
          example: "Discover Checking"
        account_Type:
          type: "string"
          description: "Type of account (checking, savings)"
          example: "Checking"
      xml:
        name: "item"